// tileData.ts
import {
  BarChart3, Sword, Users, Grid, RotateCw, Bell, Calendar,
  Glasses, Settings, FileText, Activity,
  FileBarChart2, UserCog, Clock,
  Layers, FlaskRound, FileSearch,
  AlignEndHorizontal, Target, Cpu, Brain, Database,
  Shield, Video, BookOpen,
  ClipboardList, Server, Network,
  Award,
  CheckCircle, Megaphone, GitBranch,
  Book, GraduationCap, Microscope,
  List, DownloadCloud,
  TrendingUp, ClipboardCheck,
  Edit3,
  FileStack,
  FileSliders,
  ChartNoAxesCombined,
  FileChartColumn,
  ClipboardPenLine,
  ShieldCheck
} from 'lucide-react';

export const tiles = [
  {
    title: 'Dashboard',
    permissionKey: 'dashboard_main',
    links: [
      { name: 'Management Review Dashboard', path: '/management', icon: TrendingUp, permissionKey: 'dashboard_management' },
      { name: 'Production Planning Dashboard', path: '/advanced', icon: Activity, permissionKey: 'dashboard_production' },
      { name: 'Advanced Manpower Planning Dashboard', path: '/advance', icon: AlignEndHorizontal, permissionKey: 'dashboard_manpower' },
    ],
    icon: BarChart3,
    statusText: 'Live',
    borderTopColor: 'border-t-blue-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-500 to-blue-700',
  },
  {
    title: 'Planning',
    permissionKey: 'planning_main',
    links: [
      // { name: 'Planning', path: '/planning', icon: GitBranch },
      { name: 'Plan', path: '/plan', icon: Target, permissionKey: 'planning_plan' },
      // { name: 'Plan List', path: '/planlist', icon: ClipboardList },
    ],
    icon: Calendar,
    statusText: 'Updated',
    borderTopColor: 'border-t-purple-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-500 to-purple-700',
  },
  // {
  //   title: 'Analytics',
  //   permissionKey: 'analytics_main',
  //   links: [
  //     { name: 'Analytics Graph', path: '#', icon: ChartNoAxesCombined, permissionKey: 'analytics_graph' },
  //     { name: 'Analytics Table', path: '#', icon: FileChartColumn, permissionKey: 'analytics_table' },
  //     //  { name: 'Analytics Graph', path: '/analytics', icon: ChartNoAxesCombined },
  //     // { name: 'Analytics Table', path: '/ProductionDataTable', icon: FileChartColumn },
  //   ],
  //   icon: BarChart3,
  //   statusText: 'Updated',
  //   borderTopColor: 'border-t-purple-500',
  //   iconColor: 'text-white',
  //   iconBgColor: 'bg-gradient-to-br from-purple-500 to-purple-700',
  // },
  {
    title: 'Master Employee',
    permissionKey: 'master_employee_main',
    links: [
      { name: 'Master Table', path: '/MasterTable', icon: Database, permissionKey: 'master_employee_table' },
      { name: 'Employee History Card', path: '/EmployeeHistorySearch', icon: Users, permissionKey: 'master_employee_history' },
    ],
    icon: Shield,
    statusText: 'Live',
    borderTopColor: 'border-t-yellow-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-yellow-600 to-yellow-800',
  },
  {
    title: 'Process Dojo',
    permissionKey: 'process_dojo_main',
    links: [
      { name: 'Process Dojo', path: '/ProcessDojo', icon: GraduationCap, permissionKey: 'process_dojo_dojo' },
      { name: 'Quiz Results', path: '/results-explorer', icon: ClipboardPenLine, permissionKey: 'process_dojo_quiz' },
    ],
    icon: Sword,
    statusText: 'Active',
    borderTopColor: 'border-t-blue-900',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-800 to-blue-900',
  },
  {
    title: 'Skill Matrix',
    permissionKey: 'skill_matrix_main',
    links: [
      { name: 'Skill Matrix', path: '/skillmatrix', icon: Brain, permissionKey: 'skill_matrix_matrix' },
    ],
    icon: Grid,
    statusText: 'Beta',
    borderTopColor: 'border-t-purple-800',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-800 to-purple-900',
  },
  {
    title: 'Retraining',
    permissionKey: 'retraining_main',
    links: [
      { name: 'poison cake', path: '/poison-cake', icon: ClipboardCheck, permissionKey: 'retraining_poison_cake' },
      { name: 'Retraining', path: '/retraining', icon: RotateCw, permissionKey: 'retraining_retraining' },
      // { name: 'OJT Sheet', path: '/', icon: Book },
    ],
    icon: FileText,
    statusText: 'Active',
    borderTopColor: 'border-t-black',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-gray-800 to-black',
    disabled: true,
  },
  {
    title: 'Notifications',
    permissionKey: 'notifications_main',
    links: [
      { name: 'Notification', path: '/notification', icon: Bell, permissionKey: 'notifications_notification' },
      { name: 'Approval List', path: '/approvallist', icon: CheckCircle, permissionKey: 'notifications_approval' },
    ],
    icon: Megaphone,
    statusText: 'Live',
    borderTopColor: 'border-t-green-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-green-500 to-green-700',
  },
  {
    title: 'Schedules',
    permissionKey: 'schedules_main',
    links: [
      { name: 'Multiskill Schedule', path: '/scheduling', icon: Clock, permissionKey: 'schedules_multiskill' },
      { name: 'Refresher Training Schedule', path: '/refreshment', icon: Calendar, permissionKey: 'schedules_refresher' },
    ],
    icon: Calendar,
    statusText: 'Updated',
    borderTopColor: 'border-t-yellow-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-yellow-500 to-yellow-700',
  },
  {
    title: 'AR/VR',
    permissionKey: 'ar_vr_main',
    links: [
      { name: 'AR/VR', path: '/ArVrComponent', icon: Glasses, permissionKey: 'ar_vr_ar_vr' },
    ],
    icon: Video,
    statusText: 'New',
    borderTopColor: 'border-t-purple-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-500 to-purple-700',
  },
  {
    title: 'Reports',
    permissionKey: 'reports_main',
    links: [
      { name: 'Report', path: '/report', icon: FileSearch, permissionKey: 'reports_report' },
    ],
    icon: FileBarChart2,
    statusText: 'Updated',
    borderTopColor: 'border-t-blue-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-600 to-blue-800',
  },
  {
    title: 'Level Wise Curriculum',
    permissionKey: 'level_wise_curriculum_main',
    links: [
      { name: 'Level wise curriculum', path: '/dojoTraining', icon: Layers, permissionKey: 'level_wise_curriculum_curriculum' },
      { name: 'Question Paper Settings', path: '/question-paper-setting', icon: FileText, permissionKey: 'level_wise_curriculum_question_paper' },
      { name: 'Questions Settings', path: '/questions-upload', icon: Edit3, permissionKey: 'level_wise_curriculum_questions' },
    ],
    icon: BookOpen,
    statusText: 'Active',
    borderTopColor: 'border-t-blue-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-500 to-blue-700',
  },
  {
    title: 'Machine Allocation',
    permissionKey: 'machine_allocation_main',
    links: [
      { name: 'Machine Allocation', path: '/machine-allocations', icon: Server, permissionKey: 'machine_allocation_allocation' },
      { name: 'Machines', path: '/machines', icon: Cpu, permissionKey: 'machine_allocation_machines' },
      { name: 'Allocation List', path: '/machineallocationslist', icon: FileSliders, permissionKey: 'machine_allocation_list' },
      { name: 'Biometric System', path: '/biometrics', icon: List, permissionKey: 'machine_allocation_biometric' },

    ],
    icon: Network,
    statusText: 'Updated',
    borderTopColor: 'border-t-purple-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-600 to-purple-800',
  },
  {
    title: 'Role Settings',
    permissionKey: 'role_settings_main',
    links: [
      // { name: 'List', path: '', icon: List },
      { name: 'Roles', path: '/Roles', icon: UserCog, permissionKey: 'role_settings_roles' },
      { name: 'Role Permissions', path: '/RolePermissions', icon: ShieldCheck, permissionKey: 'roles_management' },

    ],
    icon: Settings,
    statusText: 'System',
    borderTopColor: 'border-t-yellow-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-yellow-600 to-yellow-800',
  },
  {
    title: 'Exam Tool',
    permissionKey: 'exam_tool_main',
    links: [
      { name: 'Exam Tool Download', path: '#', icon: DownloadCloud, permissionKey: 'exam_tool_download' },
    ],
    icon: Award,
    statusText: 'Updated',
    borderTopColor: 'border-t-green-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-green-600 to-green-800',
  },
  {
    title: 'Method',
    permissionKey: 'method_main',
    links: [
      { name: 'Method', path: '/methodsettings', icon: FlaskRound, permissionKey: 'method_method' },
      { name: 'User Mannuals', path: '/ContentPage', icon: FileStack, permissionKey: 'method_user_manuals' },
    ],
    icon: Microscope,
    statusText: 'Updated',
    borderTopColor: 'border-t-blue-900',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-800 to-blue-900',
  },
];