// tileData.ts
import {
  BarChart3, Sword, Users, Grid, RotateCw, Bell, Calendar,
  Glasses, Settings, FileText, Activity,
  FileBarChart2, UserCog, Clock,
  Layers, FlaskRound, FileSearch,
  AlignEndHorizontal, Target, Cpu, Brain, Database,
  Shield, Video, BookOpen,
  ClipboardList, Server, Network,
  Award,
  CheckCircle, Megaphone, GitBranch,
  Book, GraduationCap, Microscope,
  List, DownloadCloud,
  TrendingUp, ClipboardCheck,
  Edit3,
  FileStack,
  FileSliders,
  ChartNoAxesCombined,
  FileChartColumn,
  ClipboardPenLine
} from 'lucide-react';

export const tiles = [
  {
    title: 'Dashboard',
    links: [
      { name: 'Management Review Dashboard', path: '/management', icon: TrendingUp },
      { name: 'Advance Manpower Planning Dashboard', path: '/advanced', icon: Activity },
      { name: 'Manpower Planning Dashboard', path: '/advance', icon: AlignEndHorizontal },
    ],
    icon: BarChart3,
    statusText: 'Live',
    borderTopColor: 'border-t-blue-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-500 to-blue-700',
  },
  {
    title: 'Planning',
    links: [
      // { name: 'Planning', path: '/planning', icon: GitBranch },
      { name: 'Plan', path: '/plan', icon: Target },
      // { name: 'Plan List', path: '/planlist', icon: ClipboardList },
    ],
    icon: Calendar,
    statusText: 'Updated',
    borderTopColor: 'border-t-purple-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-500 to-purple-700',
  },
  // {
  //   title: 'Analytics',
  //   links: [
  //     { name: 'Analytics Graph', path: '#', icon: ChartNoAxesCombined },
  //     { name: 'Analytics Table', path: '#', icon: FileChartColumn },
  //     //  { name: 'Analytics Graph', path: '/analytics', icon: ChartNoAxesCombined },
  //     // { name: 'Analytics Table', path: '/ProductionDataTable', icon: FileChartColumn },
  //   ],
  //   icon: BarChart3,
  //   statusText: 'Updated',
  //   borderTopColor: 'border-t-purple-500',
  //   iconColor: 'text-white',
  //   iconBgColor: 'bg-gradient-to-br from-purple-500 to-purple-700',
  // },
  {
    title: 'Master Employee',
    links: [
      { name: 'Master Table', path: '/MasterTable', icon: Database },
      { name: 'Employee History Card', path: '/EmployeeHistorySearch', icon: Users },
    ],
    icon: Shield,
    statusText: 'Live',
    borderTopColor: 'border-t-yellow-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-yellow-600 to-yellow-800',
  },
  {
    title: 'Process Dojo',
    links: [
      { name: 'Process Dojo', path: '/ProcessDojo', icon: GraduationCap },
      { name: 'Quiz Results', path: '/results-explorer', icon: ClipboardPenLine  },
    ],
    icon: Sword,
    statusText: 'Active',
    borderTopColor: 'border-t-blue-900',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-800 to-blue-900',
  },
  {
    title: 'Skill Matrix',
    links: [
      { name: 'Skill Matrix', path: '/skillmatrix', icon: Brain },
    ],
    icon: Grid,
    statusText: 'Beta',
    borderTopColor: 'border-t-purple-800',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-800 to-purple-900',
  },
  {
    title: 'Retraining',
    links: [
      { name: 'poison cake', path: '/poison-cake', icon: ClipboardCheck },
      { name: 'Retraining', path: '/retraining', icon: RotateCw },
      // { name: 'OJT Sheet', path: '/', icon: Book },
    ],
    icon: FileText,
    statusText: 'Active',
    borderTopColor: 'border-t-black',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-gray-800 to-black',
    disabled: true,
  },
  {
    title: 'Notifications',
    links: [
      { name: 'Notification', path: '/notification', icon: Bell },
      { name: 'Approval List', path: '/approvallist', icon: CheckCircle },
    ],
    icon: Megaphone,
    statusText: 'Live',
    borderTopColor: 'border-t-green-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-green-500 to-green-700',
  },
  {
    title: 'Schedules',
    links: [
      { name: 'Multiskill Schedule', path: '/scheduling', icon: Clock },
      { name: 'Refresher Training Schedule', path: '/refreshment', icon: Calendar },
    ],
    icon: Calendar,
    statusText: 'Updated',
    borderTopColor: 'border-t-yellow-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-yellow-500 to-yellow-700',
  },
  {
    title: 'AR/VR',
    links: [
      { name: 'AR/VR', path: '/ArVrComponent', icon: Glasses },
    ],
    icon: Video,
    statusText: 'New',
    borderTopColor: 'border-t-purple-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-500 to-purple-700',
  },
  {
    title: 'Reports',
    links: [
      { name: 'Report', path: '/report', icon: FileSearch },
    ],
    icon: FileBarChart2,
    statusText: 'Updated',
    borderTopColor: 'border-t-blue-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-600 to-blue-800',
  },
  {
    title: 'Level Wise Curriculum',
    links: [
      { name: 'Level wise curriculum', path: '/dojoTraining', icon: Layers },
      { name: 'Question Paper Settings', path: '/question-paper-setting', icon: FileText },
      { name: 'Questions Settings', path: '/questions-upload', icon: Edit3 },
    ],
    icon: BookOpen,
    statusText: 'Active',
    borderTopColor: 'border-t-blue-500',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-500 to-blue-700',
  },
  {
    title: 'Machine Allocation',
    links: [
      { name: 'Machine Allocation', path: '/machine-allocations', icon: Server },
      { name: 'Machines', path: '/machines', icon: Cpu },
      { name: 'Allocation List', path: '/machineallocationslist', icon: FileSliders },
      { name: 'Biometric System', path: '/biometrics', icon: List },

    ],
    icon: Network,
    statusText: 'Updated',
    borderTopColor: 'border-t-purple-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-purple-600 to-purple-800',
  },
  {
    title: 'Role Settings',
    links: [
      // { name: 'List', path: '', icon: List },
      { name: 'Roles', path: '/Roles', icon: UserCog },
    ],
    icon: Settings,
    statusText: 'System',
    borderTopColor: 'border-t-yellow-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-yellow-600 to-yellow-800',
  },
  {
    title: 'Exam Tool',
    links: [
      { name: 'Exam Tool Download', path: '#', icon: DownloadCloud },
    ],
    icon: Award,
    statusText: 'Updated',
    borderTopColor: 'border-t-green-600',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-green-600 to-green-800',
  },
  {
    title: 'Method',
    links: [
      { name: 'Method', path: '/methodsettings', icon: FlaskRound },
      { name: 'User Mannuals', path: '/ContentPage', icon: FileStack },
    ],
    icon: Microscope,
    statusText: 'Updated',
    borderTopColor: 'border-t-blue-900',
    iconColor: 'text-white',
    iconBgColor: 'bg-gradient-to-br from-blue-800 to-blue-900',
  },
];