# Generated by Django 5.1 on 2025-09-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='critical',
        ),
        migrations.RemoveField(
            model_name='station',
            name='ctq',
        ),
        migrations.RemoveField(
            model_name='station',
            name='marua',
        ),
        migrations.RemoveField(
            model_name='station',
            name='other',
        ),
        migrations.RemoveField(
            model_name='station',
            name='pdi',
        ),
    ]
