# Generated by Django 5.2.4 on 2025-09-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_mastertable_full_name_mastertable_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_production_plan', models.PositiveIntegerField()),
                ('total_production_actual', models.PositiveIntegerField(default=0)),
                ('total_operators_required_plan', models.PositiveIntegerField(default=0)),
                ('total_operators_required_actual', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l1', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l2', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l3', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l4', models.PositiveIntegerField(default=0)),
                ('ctq_plan_total', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l1', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l2', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l3', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l4', models.PositiveIntegerField(default=0)),
                ('ctq_actual_total', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l1', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l2', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l3', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l4', models.PositiveIntegerField(default=0)),
                ('pdi_plan_total', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l1', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l2', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l3', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l4', models.PositiveIntegerField(default=0)),
                ('pdi_actual_total', models.PositiveIntegerField(default=0)),
                ('other_plan_l1', models.PositiveIntegerField(default=0)),
                ('other_plan_l2', models.PositiveIntegerField(default=0)),
                ('other_plan_l3', models.PositiveIntegerField(default=0)),
                ('other_plan_l4', models.PositiveIntegerField(default=0)),
                ('other_plan_total', models.PositiveIntegerField(default=0)),
                ('other_actual_l1', models.PositiveIntegerField(default=0)),
                ('other_actual_l2', models.PositiveIntegerField(default=0)),
                ('other_actual_l3', models.PositiveIntegerField(default=0)),
                ('other_actual_l4', models.PositiveIntegerField(default=0)),
                ('other_actual_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factory')),
                ('hq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hq')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.line')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
                ('subline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.subline')),
            ],
        ),
    ]
