# Generated by Django 5.0.6 on 2025-09-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_machineallocationtrackingemail_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subline',
            name='subline_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subline',
            unique_together={('line', 'subline_name')},
        ),
    ]
