# Generated by Django 5.1.4 on 2025-09-03 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_subline_subline_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('question_paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_paper_name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='question_papers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.level')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.station')),
                ('subline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.subline')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='app1.questionpaper')),
            ],
        ),
        migrations.CreateModel(
            name='StationLevelQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_questionpapers', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_questionpapers', to='app1.level')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_questionpapers', to='app1.line')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_stations', to='app1.questionpaper')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_questionpapers', to='app1.station')),
                ('subline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subline_questionpapers', to='app1.subline')),
            ],
            options={
                'verbose_name': 'Station-Level Question Paper Mapping',
                'verbose_name_plural': 'Station-Level Question Paper Mappings',
                'unique_together': {('department', 'line', 'subline', 'station', 'level')},
            },
        ),
    ]
