# Generated by Django 5.2.5 on 2025-09-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_questionpaper_templatequestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='station',
        ),
    ]
