# Generated by Django 5.2.5 on 2025-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_level_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARVRTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('arvr_file', models.FileField(blank=True, null=True, upload_to='arvr_files/')),
                ('url_link', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
