# Generated by Django 5.2.5 on 2025-09-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_arvrtrainingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelWiseTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_contents', to='app1.level')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_contents', to='app1.station')),
            ],
        ),
    ]
