# Generated by Django 5.2.5 on 2025-09-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_levelwisetrainingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanchouExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShokuchouExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sho_question', models.TextField()),
                ('sho_option_a', models.CharField(max_length=255)),
                ('sho_option_b', models.CharField(max_length=255)),
                ('sho_option_c', models.CharField(max_length=255)),
                ('sho_option_d', models.CharField(max_length=255)),
                ('sho_correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HanSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('han_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='app1.hancontent')),
            ],
        ),
        migrations.CreateModel(
            name='HanTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('training_file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('han_subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app1.hansubtopic')),
            ],
        ),
        migrations.CreateModel(
            name='ShoSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sho_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sho_subtopics', to='app1.shocontent')),
            ],
        ),
        migrations.CreateModel(
            name='ShoTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sho_description', models.TextField()),
                ('training_file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('sho_subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sho_materials', to='app1.shosubtopic')),
            ],
        ),
        migrations.CreateModel(
            name='HanchouExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='hanchou', editable=False, max_length=50)),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('total_questions', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_mark_percent', models.PositiveSmallIntegerField(default=70)),
                ('passed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hanchou_results', to='app1.mastertable')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('score__lte', models.F('total_questions'))), name='score_lte_total_questions')],
            },
        ),
        migrations.CreateModel(
            name='ShokuchouExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sho_exam_name', models.CharField(default='shokuchou', editable=False, max_length=50)),
                ('sho_started_at', models.DateTimeField()),
                ('sho_submitted_at', models.DateTimeField()),
                ('sho_total_questions', models.PositiveIntegerField()),
                ('sho_score', models.PositiveIntegerField()),
                ('sho_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sho_pass_mark_percent', models.PositiveSmallIntegerField(default=70)),
                ('sho_passed', models.BooleanField(default=False)),
                ('sho_remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shokuchou_results', to='app1.mastertable')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('sho_score__lte', models.F('sho_total_questions'))), name='sho_score_lte_total_questions')],
            },
        ),
    ]
