# Generated by Django 5.2.5 on 2025-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_operatorperformanceevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcontent',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='training_file',
            field=models.FileField(blank=True, null=True, upload_to='training_files/'),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
    ]
