# Generated by Django 5.2.5 on 2025-09-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_trainingcontent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainer_id', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=100)),
                ('subline', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('process_name', models.CharField(max_length=100)),
                ('revision_date', models.DateField()),
                ('doj', models.DateField()),
                ('trainer_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tencyclepassingcriteria',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten_cycle_passing_criteria', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='tencyclepassingcriteria',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten_cycle_passing_criteria', to='app1.level'),
        ),
        migrations.CreateModel(
            name='OJTDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_days', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_days', to='app1.level')),
            ],
        ),
        migrations.CreateModel(
            name='OJTLevel2Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=200)),
                ('trainee_id', models.CharField(max_length=50, unique=True)),
                ('emp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('station_name', models.CharField(max_length=100)),
                ('line_name', models.CharField(max_length=100)),
                ('process_name', models.CharField(max_length=200)),
                ('revision_date', models.DateField()),
                ('doj', models.DateField(verbose_name='Date of Joining')),
                ('trainer_name', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_records', to='app1.level')),
            ],
        ),
        migrations.CreateModel(
            name='Level2QuantityOJTEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('plan', models.PositiveIntegerField()),
                ('production_actual', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_rejections', models.PositiveIntegerField()),
                ('ojt_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app1.ojtlevel2quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OJTTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_topics', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_topics', to='app1.level')),
            ],
        ),
        migrations.CreateModel(
            name='OJTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app1.ojtday')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app1.ojttopic')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app1.traineeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OJTPassingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Passing percentage (e.g., 60 for 60%)')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ojt_passing_criteria', to='app1.ojtday')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_passing_criteria', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_passing_criteria', to='app1.level')),
            ],
            options={
                'unique_together': {('department', 'level', 'day')},
            },
        ),
        migrations.CreateModel(
            name='OJTScoreRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_ranges', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_ranges', to='app1.level')),
            ],
            options={
                'unique_together': {('department', 'level')},
            },
        ),
    ]
