# Generated by Django 5.2.5 on 2025-09-09 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_traineeinfo_alter_tencyclepassingcriteria_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='Trainer_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('link', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='training_contents/')),
                ('link', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app1.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='Scheduled', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('employees', models.ManyToManyField(related_name='schedules', to='app1.mastertable')),
                ('training_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_topics', to='app1.curriculum')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.trainer_name')),
                ('training_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_categories', to='app1.training_category')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.venues')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('original_time', models.TimeField()),
                ('new_date', models.DateField()),
                ('new_time', models.TimeField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='app1.mastertable')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='app1.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='app1.training_category'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('rescheduled', 'Rescheduled')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reschedule_date', models.DateField(blank=True, null=True)),
                ('reschedule_time', models.TimeField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app1.mastertable')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app1.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'employee')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('category', 'topic')},
        ),
    ]
