# Generated by Django 5.2.5 on 2025-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_curriculum_trainer_name_training_category_venues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='added_to_master_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_added_to_master',
            field=models.BooleanField(default=False),
        ),
    ]
