# Generated by Django 5.2.5 on 2025-09-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_userregistration_added_to_master_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='app1.level'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
