# Generated by Django 5.2.5 on 2025-09-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_subtopic_topic_subtopic_level_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('CTQ', 'CTQ'), ('PDI', 'PDI'), ('OTHER', 'Other'), ('MARU_A', 'Maru A'), ('CRITICAL', 'Critical')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app1.station')),
            ],
        ),
    ]
