# Generated by Django 5.2.5 on 2025-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_stationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsetting',
            name='option',
            field=models.CharField(choices=[('CTQ', 'CTQ'), ('PDI', 'PDI'), ('OTHER', 'Other'), ('MARU A', 'Maru A'), ('CRITICAL', 'Critical')], max_length=10),
        ),
    ]
