# Generated by Django 5.2.1 on 2025-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_testsession_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('info', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField()),
                ('key_id', models.IntegerField()),
                ('key_sn', models.CharField(default='unknown', max_length=255)),
                ('mode', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('info', models.CharField(max_length=255)),
                ('client_timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('info', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
