# Generated by Django 5.2.5 on 2025-09-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_stationsetting_option'),
        ('app1', '0021_connectevent_keyevent_voteevent'),
    ]

    operations = [
    ]
