# Generated by Django 5.2.5 on 2025-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_merge_20250910_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
