# Generated by Django 5.2.5 on 2025-09-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_companylogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level2quantityojtevaluation',
            old_name='marks',
            new_name='production_marks',
        ),
        migrations.AddField(
            model_name='level2quantityojtevaluation',
            name='rejection_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ojtlevel2quantity',
            name='engineer_judge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ojtlevel2quantity',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='QuantityOJTScoreRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production_max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rejection_min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rejection_max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_score_ranges', to='app1.department')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_score_ranges', to='app1.level')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityPassingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_passing_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rejection_passing_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_passing_criteria', to='app1.department')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_passing_criteria', to='app1.level')),
            ],
        ),
    ]
