# Generated by Django 5.1 on 2025-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_userregistration_added_to_master_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tencycledayconfiguration",
            options={"ordering": ["level", "department", "station", "sequence_order"]},
        ),
        migrations.AlterModelOptions(
            name="tencycletopics",
            options={"ordering": ["level", "department", "station", "slno"]},
        ),
        migrations.AlterUniqueTogether(
            name="tencycledayconfiguration",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tencyclepassingcriteria",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tencycletopics",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tencycledayconfiguration",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_configurations",
                to="app1.station",
            ),
        ),
        migrations.AddField(
            model_name="tencyclepassingcriteria",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ten_cycle_passing_criteria",
                to="app1.station",
            ),
        ),
        migrations.AddField(
            model_name="tencycletopics",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ten_cycle_topics",
                to="app1.station",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tencycledayconfiguration",
            unique_together={("level", "department", "station", "day_name")},
        ),
        migrations.AlterUniqueTogether(
            name="tencyclepassingcriteria",
            unique_together={("level", "department", "station")},
        ),
        migrations.AlterUniqueTogether(
            name="tencycletopics",
            unique_together={("level", "department", "station", "slno")},
        ),
    ]
