# Generated by Django 5.1 on 2025-09-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0026_alter_tencycledayconfiguration_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorperformanceevaluation",
            name="department",
        ),
        migrations.RemoveField(
            model_name="operatorperformanceevaluation",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="operatorperformanceevaluation",
            name="level",
        ),
        migrations.RemoveField(
            model_name="operatorperformanceevaluation",
            name="station",
        ),
        migrations.AlterUniqueTogether(
            name="tencycledayconfiguration",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tencycledayconfiguration",
            name="department",
        ),
        migrations.RemoveField(
            model_name="tencycledayconfiguration",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tencycledayconfiguration",
            name="station",
        ),
        migrations.AlterUniqueTogether(
            name="tencyclepassingcriteria",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tencyclepassingcriteria",
            name="department",
        ),
        migrations.RemoveField(
            model_name="tencyclepassingcriteria",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tencyclepassingcriteria",
            name="station",
        ),
        migrations.AlterUniqueTogether(
            name="tencycletopics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tencycletopics",
            name="department",
        ),
        migrations.RemoveField(
            model_name="tencycletopics",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tencycletopics",
            name="station",
        ),
        migrations.DeleteModel(
            name="EvaluationTopicMarks",
        ),
        migrations.DeleteModel(
            name="OperatorPerformanceEvaluation",
        ),
        migrations.DeleteModel(
            name="TenCycleDayConfiguration",
        ),
        migrations.DeleteModel(
            name="TenCyclePassingCriteria",
        ),
        migrations.DeleteModel(
            name="TenCycleTopics",
        ),
    ]
