# Generated by Django 5.1 on 2025-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0028_operatorperformanceevaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorperformanceevaluation",
            name="operation_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
