# Generated by Django 5.1 on 2025-09-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0029_alter_operatorperformanceevaluation_operation_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorperformanceevaluation",
            name="process_name",
        ),
    ]
