# Generated by Django 5.1 on 2025-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0030_remove_operatorperformanceevaluation_process_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorperformanceevaluation",
            name="shift",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
