# Generated by Django 5.2.5 on 2025-09-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_marks_level2quantityojtevaluation_production_marks_and_more'),
        ('app1', '0031_alter_operatorperformanceevaluation_shift'),
    ]

    operations = [
    ]
