# Generated by Django 5.1 on 2025-09-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPassingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Required percentage (e.g., 75.00)', max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_criteria', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_criteria', to='app1.level')),
            ],
            options={
                'verbose_name_plural': 'Evaluation Passing Criteria',
                'unique_together': {('level', 'department')},
            },
        ),
    ]
