# Generated by Django 5.2.5 on 2025-09-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_merge_20250912_1030'),
        ('app1', '0033_evaluationpassingcriteria'),
    ]

    operations = [
    ]
