# Generated by Django 5.2.5 on 2025-09-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_merge_20250912_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('Evaluation', 'Evaluation'), ('OJT', 'OJT'), ('10 Cycle', '10 Cycle')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('venue', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Missed', 'Missed')], default='Pending', max_length=16)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('performance_percentage', models.FloatField(blank=True, null=True)),
                ('required_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraining_sessions', to='app1.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraining_sessions', to='app1.mastertable')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraining_sessions', to='app1.level')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraining_sessions', to='app1.station')),
            ],
            options={
                'ordering': ['employee', 'evaluation_type', 'level', 'department', 'station', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='RetrainingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('Evaluation', 'Evaluation'), ('OJT', 'OJT'), ('10 Cycle', '10 Cycle')], max_length=20)),
                ('max_count', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraining_configs', to='app1.level')),
            ],
            options={
                'unique_together': {('level', 'evaluation_type')},
            },
        ),
    ]
