# Generated by Django 5.2.5 on 2025-09-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_retrainingsession_retrainingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level2quantityojtevaluation',
            name='production_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quantitypassingcriteria',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_passing_criteria', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='quantitypassingcriteria',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_passing_criteria', to='app1.level'),
        ),
        migrations.CreateModel(
            name='QuantityScoreSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('production', 'Production'), ('rejection', 'Rejection')], max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marks', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_setups', to='app1.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_setups', to='app1.level')),
            ],
        ),
    ]
