# Generated by Django 5.2.5 on 2025-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_level2quantityojtevaluation_production_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('quality', 'Quality-Based'), ('quantity', 'Quantity-Based')], default='quality', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
