# Generated by Django 5.2.5 on 2025-09-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_assessmentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatrixDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_shape', models.CharField(choices=[('piechart', 'Pie Chart'), ('levelblock', 'Level Block')], default='piechart', max_length=20)),
            ],
            options={
                'verbose_name': 'Skill Matrix Display Setting',
                'verbose_name_plural': 'Skill Matrix Display Settings',
            },
        ),
        migrations.CreateModel(
            name='LevelColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_code', models.CharField(max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='app1.level')),
            ],
            options={
                'unique_together': {('level',)},
            },
        ),
    ]
