# Generated by Django 5.2.5 on 2025-09-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_skillmatrixdisplaysetting_levelcolour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app1.mastertable')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
            ],
        ),
    ]
