# Generated by Django 5.2.1 on 2025-09-13 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_level2quantityojtevaluation_production_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('employee_registration', 'Employee Registration'), ('level_exam_completed', 'Level Exam Completed'), ('training_added', 'Training Added'), ('training_updated', 'Training Updated'), ('training_scheduled', 'Training Scheduled'), ('training_completed', 'Training Completed'), ('training_reschedule', 'Training Reschedule'), ('refresher_training_scheduled', 'Refresher Training Scheduled'), ('refresher_training_completed', 'Refresher Training Completed'), ('hanchou_exam_completed', 'Hanchou Exam Completed'), ('shokuchou_exam_completed', 'Shokuchou Exam Completed'), ('ten_cycle_evaluation_completed', '10 Cycle Evaluation Completed'), ('ojt_completed', 'OJT Completed'), ('ojt_quantity_completed', 'OJT Quantity Completed'), ('machine_allocated', 'Machine Allocated'), ('test_assigned', 'Test Assigned'), ('evaluation_completed', 'Evaluation Completed'), ('retraining_scheduled', 'Retraining Scheduled'), ('retraining_completed', 'Retraining Completed'), ('human_body_check_completed', 'Human Body Check Completed'), ('milestone_reached', 'Milestone Reached'), ('system_alert', 'System Alert')], max_length=50)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.mastertable')),
                ('human_body_check_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.humanbodychecksession')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.level')),
                ('machine_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.machineallocation')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('retraining_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.retrainingsession')),
                ('test_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.testsession')),
                ('training_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='app1_notifi_recipie_f87d15_idx'), models.Index(fields=['notification_type'], name='app1_notifi_notific_f262d2_idx'), models.Index(fields=['created_at'], name='app1_notifi_created_6a89f2_idx')],
            },
        ),
    ]
