# Generated by Django 5.2.5 on 2025-09-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_role_alter_user_role'),
        ('app1', '0041_notification'),
    ]

    operations = [
    ]
