# Generated by Django 5.1 on 2025-09-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_skillmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industrial_experience', models.CharField(max_length=255)),
                ('kpapl_experience', models.CharField(max_length=255)),
                ('required_department_at_handover', models.CharField(max_length=255)),
                ('handover_date', models.DateField()),
                ('contractor_name', models.CharField(max_length=255)),
                ('p_and_a_name', models.CharField(max_length=255)),
                ('qa_hod_name', models.CharField(max_length=255)),
                ('is_training_completed', models.BooleanField(default=False)),
                ('gojo_incharge_name', models.CharField(max_length=255)),
                ('distributed_department_after_dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.mastertable')),
            ],
        ),
    ]
