# Generated by Django 5.2.5 on 2025-09-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_merge_0040_role_alter_user_role_0041_notification'),
        ('app1', '0043_handoversheet'),
    ]

    operations = [
    ]
