# Generated by Django 5.2.5 on 2025-09-14 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_merge_20250913_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app1.hq'),
        ),
        migrations.AddField(
            model_name='line',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app1.factory'),
        ),
        migrations.AddField(
            model_name='line',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app1.hq'),
        ),
        migrations.AddField(
            model_name='station',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.department'),
        ),
        migrations.AddField(
            model_name='station',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.factory'),
        ),
        migrations.AddField(
            model_name='station',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.hq'),
        ),
        migrations.AddField(
            model_name='station',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.line'),
        ),
        migrations.AddField(
            model_name='subline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublines', to='app1.department'),
        ),
        migrations.AddField(
            model_name='subline',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublines', to='app1.factory'),
        ),
        migrations.AddField(
            model_name='subline',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublines', to='app1.hq'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app1.factory'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='factory',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='app1.hq'),
        ),
        migrations.AlterField(
            model_name='line',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.subline'),
        ),
        migrations.AlterField(
            model_name='subline',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublines', to='app1.line'),
        ),
        migrations.AlterUniqueTogether(
            name='factory',
            unique_together={('factory_name', 'hq')},
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='factory',
            table='factory',
        ),
        migrations.AlterModelTable(
            name='hq',
            table='hq',
        ),
        migrations.AlterModelTable(
            name='line',
            table='line',
        ),
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
        migrations.AlterModelTable(
            name='subline',
            table='subline',
        ),
        migrations.CreateModel(
            name='HierarchyStructure',
            fields=[
                ('structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('structure_name', models.CharField(max_length=200)),
                ('structure_data', models.JSONField()),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_structures', to='app1.factory')),
                ('hq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_structures', to='app1.hq')),
            ],
            options={
                'db_table': 'hierarchy_structure',
            },
        ),
    ]
