# Generated by Django 5.2.5 on 2025-09-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_alter_subline_unique_together_department_hq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrainingsession',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retraining_sessions', to='app1.station'),
        ),
        migrations.CreateModel(
            name='RetrainingSessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_failure_points', models.TextField(blank=True, null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retraining_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_detail', to='app1.retrainingsession')),
            ],
            options={
                'verbose_name': 'Retraining Session Detail',
            },
        ),
    ]
