# Generated by Django 5.2.5 on 2025-09-16 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_alter_retrainingsession_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchystructure',
            name='structure_data',
        ),
        migrations.AddField(
            model_name='hierarchystructure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_structures', to='app1.department'),
        ),
        migrations.AddField(
            model_name='hierarchystructure',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_structures', to='app1.line'),
        ),
        migrations.AddField(
            model_name='hierarchystructure',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_structures', to='app1.station'),
        ),
        migrations.AddField(
            model_name='hierarchystructure',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_structures', to='app1.subline'),
        ),
    ]
