# Generated by Django 5.2.5 on 2025-09-16 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_remove_hierarchystructure_structure_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='training_topics', to='app1.level')),
                ('station', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='training_topics', to='app1.station')),
            ],
        ),
        migrations.AddField(
            model_name='levelwisetrainingcontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app1.trainingtopic'),
        ),
    ]
