# Generated by Django 5.1 on 2025-09-15 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_handoversheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('entry_mode', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_production_plan', models.PositiveIntegerField(default=0)),
                ('total_production_actual', models.PositiveIntegerField(default=0)),
                ('total_operators_available', models.PositiveIntegerField(default=0, help_text='The total operators on payroll at the start of this period (Starting Team)')),
                ('total_operators_required_plan', models.PositiveIntegerField(default=0, help_text='Operators We NEED (Plan)')),
                ('total_operators_required_actual', models.PositiveIntegerField(default=0)),
                ('attrition_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g., 2.0 for 2%', max_digits=5)),
                ('absenteeism_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g., 5.5 for 5.5%', max_digits=5)),
                ('ctq_plan_l1', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l2', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l3', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l4', models.PositiveIntegerField(default=0)),
                ('ctq_plan_total', models.PositiveIntegerField(default=0, editable=False)),
                ('ctq_actual_l1', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l2', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l3', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l4', models.PositiveIntegerField(default=0)),
                ('ctq_actual_total', models.PositiveIntegerField(default=0, editable=False)),
                ('pdi_plan_l1', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l2', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l3', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l4', models.PositiveIntegerField(default=0)),
                ('pdi_plan_total', models.PositiveIntegerField(default=0, editable=False)),
                ('pdi_actual_l1', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l2', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l3', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l4', models.PositiveIntegerField(default=0)),
                ('pdi_actual_total', models.PositiveIntegerField(default=0, editable=False)),
                ('other_plan_l1', models.PositiveIntegerField(default=0)),
                ('other_plan_l2', models.PositiveIntegerField(default=0)),
                ('other_plan_l3', models.PositiveIntegerField(default=0)),
                ('other_plan_l4', models.PositiveIntegerField(default=0)),
                ('other_plan_total', models.PositiveIntegerField(default=0, editable=False)),
                ('other_actual_l1', models.PositiveIntegerField(default=0)),
                ('other_actual_l2', models.PositiveIntegerField(default=0)),
                ('other_actual_l3', models.PositiveIntegerField(default=0)),
                ('other_actual_l4', models.PositiveIntegerField(default=0)),
                ('other_actual_total', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_plan_l1', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_plan_l2', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_plan_l3', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_plan_l4', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_actual_l1', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_actual_l2', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_actual_l3', models.PositiveIntegerField(default=0, editable=False)),
                ('bifurcation_actual_l4', models.PositiveIntegerField(default=0, editable=False)),
                ('grand_total_plan', models.PositiveIntegerField(default=0, editable=False)),
                ('grand_total_actual', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Hq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hq')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.factory')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.line')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
                ('subline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.subline')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
