# Generated by Django 5.1 on 2025-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_dailyproductiondata'),
    ]




    operations = [
        migrations.AlterField(
            model_name='handoversheet',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='gojo_incharge_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='industrial_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='kpapl_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='p_and_a_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='qa_hod_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoversheet',
            name='required_department_at_handover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
