# Generated by Django 5.2.5 on 2025-09-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_trainingtopic_levelwisetrainingcontent_topic'),
        ('app1', '0050_alter_handoversheet_contractor_name_and_more'),
    ]

    operations = [
    ]
