# Generated by Django 5.2.5 on 2025-09-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_merge_20250916_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmatrix',
            name='skill',
        ),
        migrations.AddField(
            model_name='skillmatrix',
            name='hierarchy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_matrices', to='app1.hierarchystructure'),
            preserve_default=False,
        ),
    ]
