# Generated by Django 5.2.5 on 2025-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_remove_skillmatrix_skill_skillmatrix_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManualdocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Content name/title', max_length=255)),
                ('file', models.FileField(help_text='Upload document file', upload_to='usermanual_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='operatorperformanceevaluation',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
