# Generated by Django 5.2.1 on 2025-09-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_remove_skillmatrix_skill_skillmatrix_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.line'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='app1.subline'),
        ),
    ]
