# Generated by Django 5.2.1 on 2025-09-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_questionpaper_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationlevelquestionpaper',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stationlevelquestionpaper',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_questionpapers', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='stationlevelquestionpaper',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_questionpapers', to='app1.line'),
        ),
        migrations.AlterField(
            model_name='stationlevelquestionpaper',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_questionpapers', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='stationlevelquestionpaper',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subline_questionpapers', to='app1.subline'),
        ),
    ]
