# Generated by Django 5.2.5 on 2025-09-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_usermanualdocs_and_more'),
        ('app1', '0055_alter_stationlevelquestionpaper_unique_together_and_more'),
    ]

    operations = [
    ]
