# Generated by Django 5.2.5 on 2025-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_trainingbatch_userregistration_batch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='company_of_experience',
            field=models.CharField(blank=True, help_text='Previous company name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('contractual', 'Contractual'), ('permanent', 'Permanent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='experience',
            field=models.BooleanField(default=False, help_text='Check if you have work experience'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years of experience', null=True),
        ),
    ]
