# Generated by Django 5.2.5 on 2025-09-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_remove_userregistration_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitypassingcriteria',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_passing_criteria', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='quantitypassingcriteria',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_passing_criteria', to='app1.level'),
        ),
    ]
