# Generated by Django 5.2.5 on 2025-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_alter_quantitypassingcriteria_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='line_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='process_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
