# Generated by Django 5.1 on 2025-09-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_remove_skillmatrix_skill_skillmatrix_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceManpowerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_stations', models.PositiveIntegerField(default=0)),
                ('operators_required', models.PositiveIntegerField(default=0)),
                ('operators_available', models.PositiveIntegerField(default=0)),
                ('buffer_manpower_required', models.PositiveIntegerField(default=0)),
                ('buffer_manpower_available', models.PositiveIntegerField(default=0)),
                ('attrition_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('absenteeism_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factory')),
                ('hq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hq')),
            ],
            options={
                'db_table': 'advance_manpower_dashboard',
                'unique_together': {('hq', 'factory', 'department', 'month', 'year')},
            },
        ),
    ]
