# Generated by Django 5.1 on 2025-09-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_advancemanpowerdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('new_operators_joined', models.IntegerField()),
                ('new_operators_trained', models.IntegerField()),
                ('total_training_plans', models.IntegerField()),
                ('total_trainings_actual', models.IntegerField()),
                ('total_defects_msil', models.IntegerField()),
                ('ctq_defects_msil', models.IntegerField()),
                ('total_defects_tier1', models.IntegerField()),
                ('ctq_defects_tier1', models.IntegerField()),
                ('total_internal_rejection', models.IntegerField()),
                ('ctq_internal_rejection', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factory')),
                ('hq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hq')),
            ],
        ),
    ]
