# Generated by Django 5.1 on 2025-09-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_managementreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='managementreview',
            unique_together={('hq', 'factory', 'department', 'month', 'year')},
        ),
    ]
