# Generated by Django 5.2.5 on 2025-09-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_alter_ojtlevel2quantity_line_name_and_more'),
        ('app1', '0063_alter_managementreview_unique_together'),
    ]

    operations = [
    ]
