# Generated by Django 5.2.1 on 2025-09-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_merge_20250918_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
    ]
