# Generated by Django 5.2.1 on 2025-09-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_score_department_testsession_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
