# Generated by Django 5.2.5 on 2025-09-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_alter_traineeinfo_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSkilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_skills', to='app1.mastertable')),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_skills', to='app1.hierarchystructure')),
            ],
        ),
    ]
