# Generated by Django 5.2.5 on 2025-09-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_multiskilling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineAllocationTrackingEmail',
        ),
        migrations.AlterField(
            model_name='machine',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='machineallocation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='machineallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.skillmatrix'),
        ),
        migrations.AlterUniqueTogether(
            name='machineallocation',
            unique_together={('machine', 'employee')},
        ),
    ]
