# Generated by Django 5.2.5 on 2025-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_delete_machineallocationtrackingemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='batch_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
