# Generated by Django 5.1 on 2025-09-23 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_userregistration_batch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_full_name', models.CharField(editable=False, max_length=200)),
                ('snapshot_department', models.CharField(editable=False, max_length=100)),
                ('snapshot_designation', models.CharField(editable=False, max_length=100)),
                ('snapshot_date_of_joining', models.DateField(editable=False)),
                ('station_name', models.CharField(max_length=150)),
                ('evaluation_date', models.DateField()),
                ('dojo_incharge_name', models.CharField(max_length=200)),
                ('area_incharge_name', models.CharField(max_length=200)),
                ('total_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Re-evaluation Pass', 'Re-evaluation Pass'), ('Re-evaluation Fail', 'Re-evaluation Fail'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations_in_department', to='app1.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_two_evaluations', to='app1.mastertable')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skillevaluations', to='app1.level')),
            ],
            options={
                'verbose_name': 'Skill Evaluation (Level 2)',
                'verbose_name_plural': 'Skill Evaluations (Level 2)',
                'unique_together': {('employee', 'department', 'station_name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_text', models.TextField()),
                ('initial_score', models.CharField(blank=True, choices=[('O', 'OK'), ('X', 'Not OK (NG)')], max_length=1, null=True)),
                ('reevaluation_score', models.CharField(blank=True, choices=[('O', 'OK'), ('X', 'Not OK (NG)')], max_length=1, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app1.evaluationlevel2')),
            ],
            options={
                'verbose_name': 'Evaluation Score',
                'verbose_name_plural': 'Evaluation Scores',
            },
        ),
    ]
