# Generated by Django 5.1 on 2025-09-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_evaluationlevel2_evaluationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=15)),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='FAIL', max_length=10)),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app1.mastertable')),
            ],
        ),
        migrations.CreateModel(
            name='ProductivitySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=200)),
                ('mt', models.IntegerField(default=0)),
                ('e1', models.IntegerField(default=0)),
                ('e2', models.IntegerField(default=0)),
                ('e3', models.IntegerField(default=0)),
                ('cycle_time', models.IntegerField(default=40)),
                ('actual_time', models.IntegerField(default=0)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='app1.productivityevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='QualityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=15)),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='FAIL', max_length=10)),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualityevaluations', to='app1.mastertable')),
            ],
        ),
        migrations.CreateModel(
            name='QualitySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=200)),
                ('mt', models.IntegerField(default=0)),
                ('e1', models.IntegerField(default=0)),
                ('e2', models.IntegerField(default=0)),
                ('e3', models.IntegerField(default=0)),
                ('cycle_time', models.IntegerField(default=40)),
                ('actual_time', models.IntegerField(default=0)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitysequences', to='app1.qualityevaluation')),
            ],
        ),
    ]
