# Generated by Django 5.1 on 2025-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_productivityevaluation_productivitysequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
