# Generated by Django 5.1 on 2025-09-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_mastertable_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiskilling',
            name='hierarchy',
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station'),
        ),
        migrations.AlterField(
            model_name='multiskilling',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.level'),
        ),
    ]
