# Generated by Django 5.1 on 2025-09-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_remove_multiskilling_hierarchy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_text', models.TextField(help_text='The actual text of the criterion/question.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order in which criteria appear on the form.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the criterion without deleting it.')),
                ('level', models.ForeignKey(help_text='The evaluation level this criterion belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='app1.level')),
            ],
            options={
                'verbose_name': 'Evaluation Criterion',
                'verbose_name_plural': 'Evaluation Criteria',
                'ordering': ['level', 'display_order'],
            },
        ),
    ]
