# Generated by Django 5.2.1 on 2025-10-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_question_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.station'),
        ),
    ]
