# Generated by Django 5.1 on 2025-10-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_question_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorObservanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=255)),
                ('operator_category', models.CharField(blank=True, max_length=255, null=True)),
                ('process_name', models.CharField(max_length=255)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('evaluation_start_date', models.DateField()),
                ('evaluation_end_date', models.DateField()),
                ('level', models.CharField(max_length=20)),
                ('marks', models.JSONField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('marks_obtained', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('signatures', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(unique=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
