# Generated by Django 5.1 on 2025-10-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_operatorobservancesheet_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorobservancesheet',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='observance_sheets', to='app1.topic'),
        ),
    ]
