# Generated by Django 5.2.1 on 2025-10-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_alter_traineeinfo_station'),
        ('app1', '0077_operatorobservancesheet_topics'),
    ]

    operations = [
    ]
