# Generated by Django 5.1 on 2025-10-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_alter_retrainingconfig_evaluation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorobservancesheet',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorobservancesheet',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
