# Generated by Django 5.2.1 on 2025-11-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0082_stationmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO-DRIVER', 'CO-DRIVER'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
