# Generated by Django 5.2.1 on 2025-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_alter_mastertable_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO-DRIVER', 'CO-DRIVER'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET')], help_text='Free text allowed. Suggestions available.', max_length=100, null=True),
        ),
    ]
