# Generated by Django 5.1 on 2025-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_alter_mastertable_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
