# Generated by Django 5.1 on 2025-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_alter_mastertable_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='raw_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
