# Generated by Django 5.2.1 on 2025-11-05 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0087_score_raw_answers_templatequestion_option_a_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastertable',
            options={'ordering': ['emp_id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='date_of_joining',
            field=models.DateField(blank=True, help_text='Optional – format YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO-DRIVER', 'CO-DRIVER'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET')], help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional but must be unique if provided', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='emp_id',
            field=models.CharField(help_text='Unique employee code (required)', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='first_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional but must be unique if provided', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='M / F / O or blank', max_length=1, null=True),
        ),
    ]
