# Generated by Django 5.2.1 on 2025-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_alter_mastertable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional but must be unique if provided', max_length=254, null=True),
        ),
    ]
