# Generated by Django 5.2.1 on 2025-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_alter_mastertable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO', 'CO'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET')], help_text='Optional', max_length=100, null=True),
        ),
    ]
