# Generated by Django 5.2.1 on 2025-11-05 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0090_alter_mastertable_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO-DRIVER', 'CO-DRIVER'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET'), ('CO', 'CO')], help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional but must be unique if provided', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
