# Generated by Django 5.2.1 on 2025-11-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0092_alter_mastertable_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(verbose_name='Sr.No.')),
                ('pay_code', models.CharField(max_length=20, verbose_name='PayCode')),
                ('card_no', models.CharField(max_length=20, verbose_name='Card No')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('shift', models.CharField(max_length=10, verbose_name='Shift')),
                ('start', models.TimeField(verbose_name='Start')),
                ('in_time', models.TimeField(verbose_name='In')),
                ('out_time', models.TimeField(verbose_name='Out')),
                ('hrs_works', models.TimeField(blank=True, null=True, verbose_name='Hrs Works')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('early_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='Early Arriv.')),
                ('late_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='Late Arriv.')),
                ('shift_early', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shift Early')),
                ('excess_lunch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Excess Lunch')),
                ('ot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ot')),
                ('ot_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ot Amount')),
                ('manual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('card_no', 'created_at')},
            },
        ),
    ]
