# Generated by Django 5.2.1 on 2025-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0094_biouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
