# Generated by Django 5.2.1 on 2025-11-11 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0095_alter_userregistration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='sub_department',
            field=models.CharField(blank=True, help_text='Optional – free text (e.g., Electrical, Plumbing, IT Support)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO- DRIVER', 'CO- DRIVER'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET'), ('OE', 'OE'), ('SENIOR OE', 'SENIOR OE')], help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='emp_id',
            field=models.CharField(help_text='Unique employee code (letters and numbers only)', max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must contain only letters and numbers (no spaces or symbols).', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
