# Generated by Django 5.2.1 on 2025-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0096_mastertable_sub_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, choices=[('', '--- Select Designation ---'), ('CO- DRIVER', 'CO- DRIVER'), ('DRIVER', 'DRIVER'), ('HELPER', 'HELPER'), ('MALI', 'MALI'), ('OPERATOR', 'OPERATOR'), ('PANTRY BOY', 'PANTRY BOY'), ('SUPERVISOR', 'SUPERVISOR'), ('SWEEPER', 'SWEEPER'), ('OET', 'OET'), ('OE', 'OE'), ('Sr.OE', 'Sr.OE')], help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='sub_department',
            field=models.CharField(blank=True, choices=[('', '--- Select Sub-Department ---'), ('ACTUATOR', 'ACTUATOR'), ('E/MIRROR', 'E/MIRROR'), ('IMM', 'IMM'), ('MIRROR', 'MIRROR'), ('OFF LINE', 'OFF LINE'), ('PAINT SHOP', 'PAINT SHOP'), ('Power Folding', 'Power Folding'), ('IMM PQA', 'IMM PQA'), ('PAINT SHOP PQA', 'PAINT SHOP PQA'), ('E/MIRROR PQA', 'E/MIRROR PQA'), ('OFF LINE PQA', 'OFF LINE PQA'), ('IQC', 'IQC'), ('IFC', 'IFC'), ('QA DISP. PDI', 'QA DISP. PDI'), ('QUALITY ASSURANCE', 'QUALITY ASSURANCE')], help_text='Optional – select from predefined sub-departments', max_length=150, null=True),
        ),
    ]
