# Generated by Django 5.2.1 on 2025-11-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0097_alter_mastertable_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='sub_department',
            field=models.ForeignKey(blank=True, help_text='Optional – select from predefined sub-departments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app1.line'),
        ),
    ]
