# Generated by Django 5.2.7 on 2025-11-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0098_alter_mastertable_sub_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Lathe Shop Device', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='e.g. 192.168.1.50')),
                ('port', models.IntegerField(default=80)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(default='essl', max_length=50)),
                ('password', models.CharField(default='essl', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='biouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='biometric_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='app1.biometricdevice'),
        ),
        migrations.CreateModel(
            name='BiometricEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('bio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app1.biouser')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='app1.biometricdevice')),
            ],
            options={
                'verbose_name': 'Enrolled User Log',
                'unique_together': {('bio_user', 'device')},
            },
        ),
    ]
