# Generated by Django 5.2.8 on 2025-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0100_alter_advancemanpowerdashboard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricattendance',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Os'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='card_no',
            field=models.CharField(max_length=50, verbose_name='Card No'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='early_arrival',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Early Arriv.'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='excess_lunch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Excess Lunch'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='hrs_works',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hrs Works'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='In'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='late_arrival',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Late Arriv.'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='ot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ot'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='ot_amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ot Amount'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Out'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='pay_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PayCode'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='shift_early',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shift Early'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='sr_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sr.No.'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status'),
        ),
    ]
