# Generated by Django 5.2.8 on 2025-12-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0101_biometricattendance_os_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biometricattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='biometricattendance',
            name='attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Attendance Date'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricattendance',
            unique_together={('card_no', 'attendance_date')},
        ),
    ]
