# Generated by Django 5.2.8 on 2025-12-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0102_alter_biometricattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biometricattendance',
            unique_together={('card_no', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='biometricattendance',
            name='attendance_date',
        ),
    ]
