# Generated by Django 5.1 on 2025-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0104_alter_biometricattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationscore',
            name='initial_score',
            field=models.CharField(blank=True, choices=[('O', 'OK'), ('X', 'Not OK (NG)'), ('N/A', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='reevaluation_score',
            field=models.CharField(blank=True, choices=[('O', 'OK'), ('X', 'Not OK (NG)'), ('N/A', 'Not Applicable')], max_length=3, null=True),
        ),
    ]
