# Generated by Django 5.1 on 2025-12-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0106_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('subtopic', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='stationmanager',
            name='minimum_level_required',
            field=models.CharField(blank=True, choices=[('Level 1', 'Leve 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4')], max_length=20, null=True),
        ),
    ]
