# Generated by Django 5.1 on 2025-12-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0107_actionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='subtopic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
