# Generated by Django 5.2.1 on 2025-12-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0109_actionitemrejection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advancemanpowerdashboard',
            unique_together={('hq', 'factory', 'department', 'line', 'subline', 'month', 'year')},
        ),
    ]
