# Generated by Django 5.2.7 on 2025-12-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0110_alter_advancemanpowerdashboard_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_punch', models.TimeField()),
                ('last_punch', models.TimeField()),
                ('bio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='app1.biouser')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.biometricdevice')),
            ],
            options={
                'verbose_name': 'Daily Attendance Summary',
                'ordering': ['-date', 'bio_user'],
                'unique_together': {('bio_user', 'device', 'date')},
            },
        ),
    ]
