# Generated by Django 5.2.10 on 2026-01-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0111_attendancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduledSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_date', models.DateField(help_text='The original date when employee was absent')),
                ('rescheduled_date', models.DateField()),
                ('rescheduled_time', models.TimeField()),
                ('training_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('attendance_marked', models.BooleanField(default=False)),
                ('attendance_status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10, null=True)),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_photo', models.ImageField(blank=True, help_text='Photo taken when marking attendance for rescheduled session', null=True, upload_to='rescheduled_attendance_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_sessions', to='app1.trainingbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_sessions', to='app1.userregistration')),
                ('original_day', models.ForeignKey(help_text='The day the employee was originally absent', on_delete=django.db.models.deletion.CASCADE, related_name='original_absences', to='app1.days')),
                ('training_subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_sessions', to='app1.subtopic')),
            ],
            options={
                'verbose_name': 'Rescheduled Session',
                'verbose_name_plural': 'Rescheduled Sessions',
                'ordering': ['-rescheduled_date', '-rescheduled_time'],
            },
        ),
    ]
