# Generated by Django 5.2.1 on 2026-01-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0112_rescheduledsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
