# Generated by Django 5.2.1 on 2026-02-02 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0113_userregistration_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='training_name',
        ),
        migrations.AddField(
            model_name='connectevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='completed_date',
            field=models.DateField(blank=True, help_text='Date when training was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this schedule should automatically recur'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='next_training_date_override',
            field=models.DateField(blank=True, help_text='Manually set next training date (overrides calculated date)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_schedule',
            field=models.ForeignKey(blank=True, help_text='Original schedule if this is a recurring instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='app1.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_months',
            field=models.IntegerField(blank=True, help_text='Number of months for recurrence (1-10). Null means no recurrence.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurring_schedule_created',
            field=models.BooleanField(default=False, help_text='Flag to track if recurring schedule has been created'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='topics',
            field=models.ManyToManyField(related_name='scheduled_sessions', to='app1.curriculum'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_stage',
            field=models.IntegerField(default=0, help_text='Current stage of the training flow'),
        ),
        migrations.AddField(
            model_name='score',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('rescheduled', 'Rescheduled'), ('pending', 'Pending')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='raw_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='key_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together={('test_name', 'key_id')},
        ),
        migrations.CreateModel(
            name='RefresherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(related_name='refresher_batches', to='app1.mastertable')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_batches', to='app1.schedule')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('schedule', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='RefresherQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveSmallIntegerField(default=70, help_text='Percentage required to pass')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30, help_text='Time for Pre & Post Test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_question_bank', to='app1.training_category')),
            ],
            options={
                'verbose_name': 'Refresher Question Bank',
                'verbose_name_plural': 'Refresher Question Banks',
            },
        ),
        migrations.CreateModel(
            name='RefresherQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='refresher/questions/')),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('option_a_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('option_b_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('option_c_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('option_d_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct option', max_length=1)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text="If False, this question won't appear in new tests")),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app1.refresherquestionbank')),
            ],
            options={
                'verbose_name': 'Refresher Question',
                'verbose_name_plural': 'Refresher Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RefresherTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('pre', 'Pre-Test'), ('post', 'Post-Test')], max_length=10)),
                ('mode', models.CharField(choices=[('remote', 'Remote Control'), ('individual', 'Individual (PC/Tablet)')], default='individual', max_length=10)),
                ('remote_key_id', models.CharField(blank=True, max_length=20, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to='app1.refresherbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_tests', to='app1.mastertable')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_test_sessions', to='app1.schedule')),
            ],
            options={
                'verbose_name': 'Refresher Test Session',
                'verbose_name_plural': 'Refresher Test Sessions',
                'unique_together': {('schedule', 'employee', 'test_type', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='RescheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('original_time', models.TimeField()),
                ('original_venue', models.CharField(blank=True, max_length=200, null=True)),
                ('original_trainer', models.CharField(blank=True, max_length=200, null=True)),
                ('original_status', models.CharField(choices=[('absent', 'Absent'), ('rescheduled', 'Rescheduled')], help_text='Original attendance status (absent or rescheduled)', max_length=20)),
                ('rescheduled_date', models.DateField()),
                ('rescheduled_time', models.TimeField()),
                ('reschedule_reason', models.TextField()),
                ('final_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending')], default='pending', help_text='Final attendance status after reschedule', max_length=20)),
                ('final_attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_history', to='app1.mastertable')),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_histories', to='app1.schedule')),
            ],
            options={
                'verbose_name_plural': 'Reschedule Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefresherAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.refresherquestion')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app1.refreshertestsession')),
            ],
            options={
                'unique_together': {('test_session', 'question')},
            },
        ),
    ]
