# Generated by Django 5.2.1 on 2026-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0114_remove_schedule_training_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatequestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='correct_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this question is hidden from normal selection.'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_a_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_b_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_c_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_d_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order of this question within its question paper.'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='question_lang2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='templatequestion',
            table='template_question',
        ),
    ]
