# Generated by Django 5.2.10 on 2026-02-09 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0115_alter_templatequestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoversheet',
            name='distributed_line_after_dojo',
            field=models.ForeignKey(blank=True, help_text='Line assigned after Dojo training (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_distributed_line', to='app1.line'),
        ),
        migrations.AddField(
            model_name='handoversheet',
            name='distributed_station_after_dojo',
            field=models.ForeignKey(blank=True, help_text='Station assigned after Dojo training (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_distributed_station', to='app1.station'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='station',
            field=models.ForeignKey(blank=True, help_text="Employee's current Station", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app1.station'),
        ),
    ]
