# Generated by Django 5.2.10 on 2026-02-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0116_handoversheet_distributed_line_after_dojo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertable',
            name='station',
        ),
    ]
