# Generated by Django 5.2.10 on 2026-02-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0117_remove_mastertable_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='station',
            field=models.ForeignKey(blank=True, help_text="Employee's current Station", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app1.station'),
        ),
    ]
