# Generated by Django 5.2.10 on 2026-02-16 05:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0118_mastertable_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Defect category name (e.g., Appearance, Dimension)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Defect Category',
                'verbose_name_plural': 'Defect Categories',
                'db_table': 'defect_category',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('defect_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('defect_name', models.CharField(help_text='Specific defect name (e.g., Scratch, Dent, Over Size)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this defect type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this defect type is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent defect category', on_delete=django.db.models.deletion.CASCADE, related_name='defect_types', to='app1.defectcategory')),
            ],
            options={
                'verbose_name': 'Defect Type',
                'verbose_name_plural': 'Defect Types',
                'db_table': 'defect_type',
                'ordering': ['category__category_name', 'defect_name'],
                'unique_together': {('defect_name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PoisonCakeTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField(help_text='Date when the test was conducted')),
                ('model_name', models.CharField(help_text='Model/Product name being tested (e.g., KT-001)', max_length=100)),
                ('total_parts_before', models.IntegerField(help_text='Total number of parts before test', validators=[django.core.validators.MinValueValidator(0)])),
                ('ok_parts_before', models.IntegerField(help_text='Number of OK parts before test', validators=[django.core.validators.MinValueValidator(0)])),
                ('reject_parts_before', models.IntegerField(help_text='Number of reject parts before test (auto-calculated)', validators=[django.core.validators.MinValueValidator(0)])),
                ('ok_parts_after', models.IntegerField(help_text='Number of OK parts found by operator after inspection', validators=[django.core.validators.MinValueValidator(0)])),
                ('reject_parts_after', models.IntegerField(help_text='Number of reject parts found by operator after inspection', validators=[django.core.validators.MinValueValidator(0)])),
                ('test_judgment', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], help_text='Test result: OK or NOT OK (auto-calculated)', max_length=10)),
                ('re_inspection_qty', models.IntegerField(blank=True, help_text='Quantity to be re-inspected (required if test fails)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes about the test', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department where test was conducted', on_delete=django.db.models.deletion.PROTECT, related_name='poison_tests', to='app1.department')),
                ('operator', models.ForeignKey(help_text='Employee who performed the test', on_delete=django.db.models.deletion.PROTECT, related_name='poison_tests', to='app1.mastertable')),
                ('station', models.ForeignKey(help_text='Specific station where test was conducted', on_delete=django.db.models.deletion.PROTECT, related_name='poison_tests', to='app1.station')),
            ],
            options={
                'verbose_name': 'Poison Cake Test',
                'verbose_name_plural': 'Poison Cake Tests',
                'db_table': 'poison_cake_test',
                'ordering': ['-test_date', '-test_id'],
            },
        ),
        migrations.CreateModel(
            name='PlantedDefect',
            fields=[
                ('planted_defect_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Number of parts with this defect', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_category', models.ForeignKey(help_text='Category of the defect', on_delete=django.db.models.deletion.PROTECT, related_name='planted_defects', to='app1.defectcategory')),
                ('defect_type', models.ForeignKey(help_text='Specific type of defect', on_delete=django.db.models.deletion.PROTECT, related_name='planted_defects', to='app1.defecttype')),
                ('test', models.ForeignKey(help_text='The test this defect belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='planted_defects', to='app1.poisoncaketest')),
            ],
            options={
                'verbose_name': 'Planted Defect',
                'verbose_name_plural': 'Planted Defects',
                'db_table': 'planted_defect',
                'ordering': ['test', 'defect_category', 'defect_type'],
            },
        ),
        migrations.AddIndex(
            model_name='poisoncaketest',
            index=models.Index(fields=['test_date'], name='poison_cake_test_da_8bd98e_idx'),
        ),
        migrations.AddIndex(
            model_name='poisoncaketest',
            index=models.Index(fields=['test_judgment'], name='poison_cake_test_ju_987000_idx'),
        ),
        migrations.AddIndex(
            model_name='poisoncaketest',
            index=models.Index(fields=['operator'], name='poison_cake_operato_f1ffdb_idx'),
        ),
        migrations.AddIndex(
            model_name='poisoncaketest',
            index=models.Index(fields=['department'], name='poison_cake_departm_41233a_idx'),
        ),
    ]
