# Generated by Django 5.2.10 on 2026-02-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0119_defectcategory_defecttype_poisoncaketest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poisoncaketest',
            name='level',
            field=models.ForeignKey(default=1, help_text='Level at which test was conducted', on_delete=django.db.models.deletion.PROTECT, related_name='poison_tests', to='app1.level'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='poisoncaketest',
            index=models.Index(fields=['level'], name='poison_cake_level_i_045b6b_idx'),
        ),
    ]
