# Generated by Django 5.2.10 on 2026-02-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0120_poisoncaketest_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTestSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_test_date', models.DateField(help_text='Date of last completed test')),
                ('next_test_date', models.DateField(help_text='Scheduled date for next test (last_test + 90 days)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='app1.mastertable')),
                ('last_test', models.ForeignKey(help_text='The test that triggered this schedule', on_delete=django.db.models.deletion.PROTECT, related_name='next_schedules', to='app1.poisoncaketest')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='app1.level')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='app1.station')),
            ],
            options={
                'verbose_name': 'Recurring Test Schedule',
                'verbose_name_plural': 'Recurring Test Schedules',
                'db_table': 'recurring_test_schedule',
                'ordering': ['next_test_date'],
                'indexes': [models.Index(fields=['next_test_date'], name='recurring_t_next_te_e65137_idx'), models.Index(fields=['status'], name='recurring_t_status_54deb3_idx'), models.Index(fields=['employee'], name='recurring_t_employe_51fc86_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReInspectionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('failed_date', models.DateField(help_text='Date when test failed')),
                ('failed_score', models.DecimalField(decimal_places=2, help_text='Score percentage from failed test', max_digits=5)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date scheduled for re-inspection', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_test', models.ForeignKey(blank=True, help_text='The re-inspection test (if completed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reinspections', to='app1.poisoncaketest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinspection_plans', to='app1.mastertable')),
                ('failed_test', models.ForeignKey(help_text='The test that failed', on_delete=django.db.models.deletion.PROTECT, related_name='reinspection_plans', to='app1.poisoncaketest')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinspection_plans', to='app1.level')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinspection_plans', to='app1.station')),
            ],
            options={
                'verbose_name': 'Re-Inspection Plan',
                'verbose_name_plural': 'Re-Inspection Plans',
                'db_table': 'reinspection_plan',
                'ordering': ['-failed_date'],
                'indexes': [models.Index(fields=['status'], name='reinspectio_status_ec5736_idx'), models.Index(fields=['employee'], name='reinspectio_employe_3f0d54_idx'), models.Index(fields=['scheduled_date'], name='reinspectio_schedul_790cb3_idx')],
            },
        ),
    ]
