# Generated by Django 5.2.10 on 2026-02-19 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0122_poisoncaketest_evaluation_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterTestCategoryResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('found_qty', models.IntegerField(default=0, help_text='How many defects operator found in this category', validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(help_text='Defect category', on_delete=django.db.models.deletion.PROTECT, related_name='after_test_results', to='app1.defectcategory')),
                ('test', models.ForeignKey(help_text='The test this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='after_test_category_results', to='app1.poisoncaketest')),
            ],
            options={
                'db_table': 'after_test_category_result',
                'ordering': ['test', 'category'],
                'unique_together': {('test', 'category')},
            },
        ),
    ]
