# Generated by Django 5.2.10 on 2026-02-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0123_aftertestcategoryresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtestschedule',
            name='is_first_time',
            field=models.BooleanField(default=False, help_text="True if this is the employee's first scheduled test (no prior test exists)"),
        ),
        migrations.AlterField(
            model_name='recurringtestschedule',
            name='last_test',
            field=models.ForeignKey(blank=True, help_text='The test that triggered this schedule (null for first-time scheduling)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_schedules', to='app1.poisoncaketest'),
        ),
        migrations.AlterField(
            model_name='recurringtestschedule',
            name='last_test_date',
            field=models.DateField(blank=True, help_text='Date of last completed test (null for first-time scheduling)', null=True),
        ),
        migrations.AlterField(
            model_name='recurringtestschedule',
            name='next_test_date',
            field=models.DateField(help_text='Scheduled date for next/first test'),
        ),
        migrations.AddIndex(
            model_name='recurringtestschedule',
            index=models.Index(fields=['is_first_time'], name='recurring_t_is_firs_d55868_idx'),
        ),
    ]
