# Generated by Django 5.2.10 on 2026-02-21 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0124_recurringtestschedule_is_first_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancemanpowerdashboard',
            name='absenteeism_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advancemanpowerdashboard',
            name='attrition_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
