# Generated by Django 5.2.10 on 2026-02-21 11:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0125_alter_advancemanpowerdashboard_absenteeism_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='associate_attrition',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='oet_attrition',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
