# Generated by Django 5.2.10 on 2026-02-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0126_advancemanpowerdashboard_associate_attrition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oet', models.PositiveIntegerField(default=0)),
                ('associate', models.PositiveIntegerField(default=0)),
                ('overall', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
