# Generated by Django 5.2.10 on 2026-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0127_attritionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attritionrecord',
            name='associate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='attritionrecord',
            name='oet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='attritionrecord',
            name='overall',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
