# Generated by Django 5.2.6 on 2026-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0129_alter_productivityevaluation_evaluation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
