# Generated by Django 5.2.1 on 2026-04-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0130_score_test_date_testsession_test_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='app1.biouser')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.biometricdevice')),
            ],
            options={
                'verbose_name': 'Individual Punch Log',
                'ordering': ['-punch_time'],
            },
        ),
    ]
